import Head from 'next/head'
import Script from 'next/script'
import style from '../styles/Index.module.css'

export default function Home() {

  // if (typeof window !== "undefined") {
  //   VanillaTilt.init(document.querySelector(".home"), {
  //     "max": 25,
  //     "speed": 400
  //   });
  // }

  return (
    <>
      <Head>
        <title>Kriterial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
        <script type="text/javascript" src="../style/vanilla-tilt.js"></script>
      </Head>

      {/* <div className={style.ticker_wrap}>
        <div className={style.ticker}>
          <div className={style.tickerItemUp}><span className={style.quoteUp}>ERA</span>  123.234 1.2%</div>
          <div className={style.tickerItemDown}><span className={style.quoteDown}>ERA</span>   20.543 -5.2%</div>
          <div className={style.tickerItemUp}><span className={style.quoteUp}>ERA</span>   523.234 0.0%</div>
          <div className={style.tickerItemDown}><span className={style.quoteDown}>ERA</span>   89.65 -3.4%</div>
          <div className={style.tickerItemUp}><span className={style.quoteUp}>ERA</span>  123.234 1.2%</div>
          <div className={style.tickerItemDown}><span className={style.quoteDown}>ERA</span>   20.543 -5.2%</div>
          <div className={style.tickerItemUp}><span className={style.quoteUp}>ERA</span>   523.234 0.0%</div>
          <div className={style.tickerItemDown}><span className={style.quoteDown}>ERA</span>   89.65 -3.4%</div>
        </div>
      </div> */}

      <div className={style.main}>
        <div className={style.home_section}>
          <div className={style.home}>
            <p>
              <h1>Kriterial</h1>
              <br />
              <h3>
                Suitable art for all pockets
              </h3>
            </p>
          </div>
        </div>

      </div >
    </>
  )
}
