import Head from 'next/head'
import React, { useState } from 'react'
import style from '../styles/Index.module.css'
import Modal from '../components/modal'

const image = "";

export default function Home() {

  const [showModal, setShowModal] = useState(false);

  const openModal = (img) => {
    image = img
    setShowModal(prev => !prev)
  }

  return (
    <>
      <Head>
        <title>Kriterial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      {/* <div className={style.ticker_wrap}>
        <div className={style.ticker}>
          <div className={style.tickerItemUp}><span className={style.quoteUp}>ERA</span>  123.234 1.2%</div>
          <div className={style.tickerItemDown}><span className={style.quoteDown}>ERA</span>   20.543 -5.2%</div>
          <div className={style.tickerItemUp}><span className={style.quoteUp}>ERA</span>   523.234 0.0%</div>
          <div className={style.tickerItemDown}><span className={style.quoteDown}>ERA</span>   89.65 -3.4%</div>
          <div className={style.tickerItemUp}><span className={style.quoteUp}>ERA</span>  123.234 1.2%</div>
          <div className={style.tickerItemDown}><span className={style.quoteDown}>ERA</span>   20.543 -5.2%</div>
          <div className={style.tickerItemUp}><span className={style.quoteUp}>ERA</span>   523.234 0.0%</div>
          <div className={style.tickerItemDown}><span className={style.quoteDown}>ERA</span>   89.65 -3.4%</div>
        </div>
      </div> */}

      <div className={style.main}>

        <div className={style.home_section}>
          <div className={style.home}>
            <p>
              <h1>Kriterial</h1>
              <br />
              <h3>
                Suitable art for all pockets
              </h3>
            </p>
          </div>
        </div>

        <Modal showModal={showModal} setShowModal={setShowModal} image={image} />

        <div className={style.gallery}>
          <div className={style.gallery_item}>
            <div className={style.kriterialTag}>K</div>
            <img src='test.jpg' onClick={ () => openModal("test.jpg")}/>
          </div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
          <div className={style.gallery_item}></div>
        </div>

      </div >
    </>
  )
}
